docs(verb): small documentation changes
pboyer/verb pull request #67
Opened 2024-10-01 04:22 UTC by z3dev

As the title says.

2024-10-01 13:26 UTC, pboyer requested changes

2024-10-01 13:26 UTC, pboyer commented on src/verb/core/Vec.hx
> +// Tools for working with vertices
Should be vectors

2024-10-16 11:47 UTC, z3dev commented
@pboyer The changes have been made. Please review.

of course, you have to push the document changes to the website.

please publish the latest release as well.

2024-10-20 06:23 UTC, z3dev commented
@pboyer another small change... should help VERB gain some popularity :)

2024-10-31 09:02 UTC, z3dev commented
@pboyer thanks for the new build.

if you like these small changes then everything is ready for pushing to NOM.

2024-11-05 11:13 UTC, z3dev commented
🙏

2024-11-23 12:05 UTC, z3dev commented
@pboyer was there anything missing? Any feedback?

2025-04-02 13:55 UTC, merged